name: CI
on: [push, pull_request]

jobs:
  test-example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/libextism

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Compile example
        run: |
          npm i -g assemblyscript
          asc example.ts --outFile example.wasm --use abort=example/myAbort

      - name: Test example
        run: |
          TEST=$(extism call example.wasm --input "this is a test" --set-config='{"thing": "1", "a": "b"}' count_vowels)
          echo $TEST | grep '"count": 4'
          echo $TEST | grep '"config": "1"'
          echo $TEST | grep '"a": "this is var a"'
